abbr gs 'git status'
abbr l 'ls -CF'
abbr grepi 'grep -i'
abbr ff 'run firefox -no-remote'
abbr lf 'll -F'
abbr cam '~/code/ionic-camera/CAM'
abbr gcia 'git commit --amend'
abbr gadd 'git add'
abbr gdc 'git diff --cached'
abbr gls 'git ls'
abbr grm 'git rm'
abbr gd 'git diff'
abbr dotfiles '~/code/dotfiles/'
abbr df 'df -h'
abbr gbr 'git branch'
abbr gdns 'git diff --name-status'
abbr gdcns 'git diff --cached --name-status'
abbr subl 'run subl'
abbr disp 'setenv DISPLAY'
