abbr grepi 'grep -i'
abbr ff 'run firefox -no-remote'
abbr lf 'll -F'
abbr cam '~/code/ionic-camera/CAM'
abbr gcia 'git commit --amend'
abbr gadd 'git add'
abbr gdc 'git diff --cached'
abbr gls 'git ls'
abbr grm 'git rm'
abbr gd 'git diff'
abbr dotfiles '~/code/dotfiles/'
abbr df 'df -h'
abbr gbr 'git branch'
abbr gdns 'git diff --name-status'
abbr gdcns 'git diff --cached --name-status'
abbr subl 'run subl'
abbr disp 'setenv DISPLAY'
abbr emulator 'emulator -force-32bit'
abbr free 'free -h'
abbr gpull 'git pull'
abbr gsh 'git show'
abbr unset 'set -e'
abbr gps 'git push'
abbr gp 'git pull'
abbr rssowl 'run rssowl'
abbr glso 'git log --oneline'
abbr gs 'git status'
abbr l 'ls -CF'
abbr vip 'vim -p'
abbr vir 'vim -R'
abbr vipr 'vim -pR'
abbr gco 'git checkout'
abbr pac pacmatic
abbr pacn 'pacmatic --needed'
abbr paci 'pacmatic --needed -S'
abbr pacu 'pacmatic -Syu'
abbr pacs 'pacmatic -Ss'
abbr pacsi 'pacmatic -Si'
abbr pacqi 'pacmatic -Qi'
abbr dsrc '/data/src'
abbr grem 'git remote'
abbr b bash
abbr lg llg
abbr bc 'bc -l'
abbr nxa '/etc/nginx/sites-available'
abbr nxe '/etc/nginx/sites-enabled'
abbr VL '/var/log'
