abbr grepi 'grep -i'
abbr ff 'run firefox -no-remote'
abbr lf 'll -F'
abbr gcia 'git commit --amend'
abbr gadd 'git add'
abbr gdc 'git diff --cached'
abbr gls 'git ls'
abbr grm 'git rm'
abbr gd 'git diff'
abbr df 'df -h'
abbr gbr 'git branch'
abbr gdns 'git diff --name-status'
abbr gdcns 'git diff --cached --name-status'
abbr subl 'run subl'
abbr disp 'setenv DISPLAY'
abbr emulator 'emulator -force-32bit'
abbr free 'free -h'
abbr gpull 'git pull'
abbr gsh 'git show'
abbr unset 'set -e'
abbr rssowl 'run rssowl'
abbr glso 'git log --oneline'
abbr gs 'git status'
abbr l 'ls -CF'
abbr vip 'vim -p'
abbr vir 'vim -R'
abbr vipr 'vim -pR'
abbr gco 'git checkout'
abbr pac pacmatic
abbr pacn 'pacmatic --needed'
abbr paci 'pacmatic --needed -S'
abbr pacs 'pacmatic -Ss'
abbr pacsi 'pacmatic -Si'
abbr pacqi 'pacmatic -Qi'
abbr dsrc '/data/src'
abbr grem 'git remote'
abbr b bash
abbr lg llg
abbr bc 'bc -l'
abbr nxa '/etc/nginx/sites-available'
abbr nxe '/etc/nginx/sites-enabled'
abbr VL '/var/log'
abbr pacu 'sudo pacmatic -Syu'
abbr mysqli 'mysql --auto-rehash'
abbr gcl 'git clone'
abbr t tmux
abbr v 'vim -p'
abbr g git
abbr gt 'git tag'
abbr gp 'git pull --tags'
abbr gf 'git fetch --tags'
abbr s3 'aws s3'
abbr gps 'git push'
abbr gpst 'git push --tags'
abbr lsd 'command ls -d */'
abbr grep2 'grep -d skip'
abbr grep2i 'grep -d skip -i'
abbr ackn 'ack -n'
abbr grepc 'grep --color=always'
abbr gm 'git merge'
abbr gcob 'git checkout -b'
abbr gbl 'git blame'
abbr gres 'git reset'
